### ISSUE TITLE
Focus defaults to tag field after 1st task created

### ISSUE THREAD

**Issue by jonkohlmeier** [stanlemon/blueprint-taskmanager#5]
If you are starting from a clean slate and create a task by hitting enter, the Tags input is in focus for the next create task action. 

This is resolved going forward for tasks 3 and following where the task name input is set to focus. 

Browser: Safari 13.0.1

**Comment by stanlemon** [comment]
I think the tabbing/enter behavior is a bit more normal following #951123e - if you still see wonkiness let me know by reopening the issue.
